### ISSUE TITLE
Adding the C-stick

### ISSUE THREAD

**Issue by fernandoni13** [colpasus/UnoSmashbox#1]
Hi,

Great project! I'm trying to copy what you did in an Arduino mega with an ATmega16U2, but I also wanted to add the C-stick for smash. I wrote it the same way as everything else you had already done:

if (!digitalRead (RightStick_Top_pin))     controllerData.rightStickY=0;
if (!digitalRead (RightStick_Down_pin))     controllerData.rightStickY=255;
if (!digitalRead (RightStick_Left_pin))     controllerData.rightStickX=0;
if (!digitalRead (RightStick_Right_pin))     controllerData.rightStickX=255;

And it works fine in debug mode. However, when I connect it to the Nintendo Switch, it doesn't register the C-stick buttons. Everything else works fine, the tilt button changes the angle of the left stick, etc.

Any idea what is missing?

**Comment by fernandoni13** [comment]
It also requires to generate a new hex file so the nintendo switch reads the values for the C-stick

**Comment by colpasus** [comment]
Hi Fernandoni13. When I started the project  I thought about to program the c-stick but I undestood that it required 4 new buttons to add to the box and I posponed this to the end of the project.

In my last version (not uploaded yet, sry), I've included a couple of new buttons, the most important is a fast smash button that emules 2 buttons pressing  at the same time and maybe it's what you are looking for.

Other button executes a IDJ (instant double jump), it works fine but I'm not good enough to improve my game with it, anyway it's cool :)

Other new button is used for a small jump (like a tilt button to go slow) that allows a small jump with no mistakes always.

I'll upload videos and code as soon as possible.

**Comment by fernandoni13** [comment]
Hi colpases,
Thanks for your answer. I had a friend help me to solve the problem, I have a version running with the 4 buttons for the C-stick now. I use these buttons for tilt attacks. I perform smash attacks by pressing the direction and A at the same time, so I'll not add a button for that. Also, I perform the small jump by either pressing the button really fast or pressing two jump buttons together. So I think I'll use as is.
About the IDJ, I think only some characters (like cap falcon) really benefit from it, so I don't know if your main should even use it. I happen to play with cap falcon, so that interests me a lot XD
All in all, I wanted to say that your project is really cool and I'm very glad you put it to everyone in github. Thank you!

Best regards,

ir. Fernando F. de Mendonca FilhoPhD candidate at TUDelft
Materials & Environment
Civil Engineering and Geosciences
Please consider the environment before printing this email
 

    On Tuesday, 21 February 2023 at 12:52:32 CET, colpasus ***@***.***> wrote:  
 
 


Hi Fernandoni13. When I started the project I thought about to program the c-stick but I undestood that it required 4 new buttons to add to the box and I posponed this to the end of the project.

In my last version (not uploaded yet, sry), I've included a couple of new buttons, the most important is a fast smash button that emules 2 buttons pressing at the same time and maybe it's what you are looking for.

Other button executes a IDJ (instant double jump), it works fine but I'm not good enough to improve my game with it, anyway it's cool :)

Other new button is used for a small jump (like a tilt button to go slow) that allows a small jump with no mistakes always.

I'll upload videos and code as soon as possible.
